# Generated by Django 5.2.17 on 2026-08-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MELAM', 'Melam'), ('CRACKERS', 'Crackers'), ('THER', 'Ther'), ('DECORATION', 'Decoration'), ('SOUND', 'Sound System'), ('ELECTRICIAN', 'Electrician'), ('PRIEST', 'Priest'), ('OTHER', 'Other')], max_length=30)),
                ('contact_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
