# Generated by Django 5.2.17 on 2026-08-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('GALLERY', 'Gallery'), ('FESTIVAL', 'Festival')], max_length=20),
        ),
    ]
