# Generated by Django 5.2.17 on 2026-08-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('FESTIVAL', 'Festival'), ('GALLERY', 'Gallery'), ('ANNOUNCEMENT', 'Announcement'), ('PAYMENT', 'Payment Reminder')], max_length=20),
        ),
    ]
