# Generated by Django 5.2.17 on 2026-08-28 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('MELAM', 'Melam'), ('CRACKERS', 'Crackers'), ('DECORATION', 'Decoration'), ('SOUND', 'Sound System'), ('THER', 'Ther'), ('FOOD', 'Food'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='festivals.festival')),
            ],
        ),
    ]
