# Generated by Django 5.2.17 on 2026-08-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MELAM', 'Melam'), ('CRACKERS', 'Crackers'), ('DECORATION', 'Decoration'), ('SOUND', 'Sound System'), ('THER', 'Ther'), ('FOOD', 'Food'), ('ADVANCE', 'Advance'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
