# Generated by Django 5.2.17 on 2026-08-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('MELAM', 'Melam'), ('CRACKERS', 'Crackers'), ('DECORATION', 'Decoration'), ('SOUND', 'Sound System'), ('THER', 'Ther'), ('FOOD', 'Food'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
